version: "3.7"
services: 
    api-base-juros:
        container_name: api-base-juros
        restart: on-failure
        image: api-base-juros
        build:
          context: .
          dockerfile: ./src/ApiBaseJuros/Dockerfile
        ports:
          - '5005:80'
    api-calculo:
        container_name: api-calculo
        restart: on-failure
        image: api-calculo
        build:
            context: .
            dockerfile: ./src/ApiCalculo/Dockerfile
        ports:
            - '5006:80'